version: "3.7"

services:
  blahblah_frontend:
    container_name: blahblah_frontend
    build:
      context: ./frontend/blahblah/
      dockerfile: dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_webserver:
    container_name: blahblah_webserver
    build:
      context: ./backend/WebServer/
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_api_gateway:
    container_name: blahblah_api_gateway
    build:
      context: ./backend/gateway/
      dockerfile: dockerfile
    ports:
      - "8888:8080"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  envoy:
    image: envoyproxy/envoy-dev
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - /home/ubuntu/blahblah.movebxeax.me/fullchain1.pem:/home/ubuntu/blahblah.movebxeax.me/fullchain1.pem
      - /home/ubuntu/blahblah.movebxeax.me/privkey1.pem:/home/ubuntu/blahblah.movebxeax.me/privkey1.pem

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
      - blahblah_net

  openvidu_server:
    image: openvidu/openvidu-server-kms
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=MY_SECRET
    networks:
      - default
      - blahblah_net

networks:
  blahblah_net:
    driver: bridge