version: "3.7"

services:
  blahblah_frontend:
    container_name: blahblah_frontend
    build:
      context: ./frontend/blahblah/
      dockerfile: dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  blahblah_webserver:
    container_name: blahblah_webserver
    build:
      context: ./backend/WebServer/
      dockerfile: dockerfile
    ports:
      - "8888:8080"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    container_name: db-mysql
    volumes:
      - ssafy_web_db-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssafy_web_db
    ports:
      - "3336:3306"

volumes:
  ssafy_web_db-mysql-data:

networks:
  blahblah_net:
    driver: bridge