version: "3.7"

services:
  blahblah_frontend:
    container_name: blahblah_frontend
    build:
      context: ./frontend/blahblah/
      dockerfile: dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_webserver:
    container_name: blahblah_webserver
    build:
      context: ./backend/WebServer/
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_api_gateway:
    container_name: blahblah_api_gateway
    build:
      context: ./backend/gateway/
      dockerfile: dockerfile
    ports:
      - "8888:8080"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  envoy:
    image: envoyproxy/envoy-dev
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
    environment:
      ENVOY_UID: 0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/live/blahblah.movebxeax.me/privkey.pem:/etc/letsencrypt/live/blahblah.movebxeax.me/privkey.pem
      - /etc/letsencrypt/live/blahblah.movebxeax.me/fullchain.pem:/etc/letsencrypt/live/blahblah.movebxeax.me/fullchain.pem
      - /etc/letsencrypt/live/ov.blahblah.movebxeax.me/privkey.pem:/etc/letsencrypt/live/ov.blahblah.movebxeax.me/privkey.pem
      - /etc/letsencrypt/live/ov.blahblah.movebxeax.me/fullchain.pem:/etc/letsencrypt/live/ov.blahblah.movebxeax.me/fullchain.pem

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
      - blahblah_net

  openvidu-server:
    container_name: blahblah-openvidu-server
    build:
      context: ./openvidu-server
      dockerfile: dockerfile
    restart: on-failure
    network_mode: host
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    ports:
      - "4443:4443"
    volumes:
      - ./coturn:/run/secrets/coturn
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
      - ${OPENVIDU_RECORDING_CUSTOM_LAYOUT}:${OPENVIDU_RECORDING_CUSTOM_LAYOUT}
      - ${OPENVIDU_CDR_PATH}:${OPENVIDU_CDR_PATH}
    env_file:
      - .env
    environment:
      - SERVER_SSL_ENABLED=true
      - SERVER_PORT=4443
      - KMS_URIS=["ws://blahblah.movebxeax.me:8888/kurento"]
      - COTURN_IP=${COTURN_IP:-auto-ipv4}
      - COTURN_PORT=${COTURN_PORT:-3478}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

networks:
  blahblah_net:
    driver: bridge