version: "3.7"

services:
  blahblah_frontend:
    container_name: blahblah_frontend
    build:
      context: ./frontend/blahblah/
      dockerfile: dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
